### ISSUE TITLE
VE Modifications for Adjusting Non-Work Parking Costs

### ISSUE THREAD

**Issue by goreaditya** [gregorbj/OregonDOT-VisionEval#3]
The parking cost model assumes that non-work travel to a Bzone pays for parking if a parking cost has been assigned to a Bzone. This approach does not allow modeling of a scenario where workers pay for their parking but shoppers (i.e. non-work) do not.

Details are posted on the following link:
https://github.com/gregorbj/OregonDOT-VisionEval/blob/master/documents/drafts/Non-Work_Parking_Mods.md

**Comment by gregorbj** [comment]
This has been addressed. See response to pull  request.
